name: Upload .flatpakref to release

on:
  release:
    types: published

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    permissions:
      contents: write

    steps:
      - name: Download .flatpakref from Flathub
        uses: suisei-cn/actions-download-file@v1.4.0
        with:
          url: "https://dl.flathub.org/repo/appstream/org.v1993.NXDumpClient.flatpakref"
          target: release/
          retry-times: 10

      - name: Upload files to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
