name: Release flatpaks

on:
  workflow_run:
    workflows: [Flatpak]
    types: [completed]

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2.28.0
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          run_id: ${{ github.event.workflow_run.id }}
          workflow: Flatpak
          path: artifacts

      - name: Rename flatpaks appropriately
        shell: bash
        run: |
          mkdir upload
          find artifacts -mindepth 1 -type d -exec sh -c 'cp "$0"/nxdumpclient.flatpak upload/$(basename "$0").flatpak' {} \;
          echo "Files to upload:"
          find upload -type f -printf '%f\n'

      - name: Upload artifacts to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: upload/*
